// Russian translations, keyed by the Uzbek source text used in the components.
export const RU = {
  "Agar bu email ro'yxatdan o'tgan bo'lsa, parolni tiklash havolasi yuborildi. Pochtangizni tekshiring.": "Если этот email зарегистрирован, мы отправили ссылку для восстановления пароля. Проверьте почту.",
  "Arzonroq": "Сначала дешёвые",
  "Baho": "Оценка",
  "Baho 1 dan 5 gacha bo'lishi kerak": "Оценка должна быть от 1 до 5",
  "Baholash": "Оценить",
  "Bekor qilish": "Отменить",
  "Bepul": "Бесплатно",
  "Bosh sahifa": "Главная",
  "Bu email allaqachon ro'yxatdan o'tgan": "Этот email уже зарегистрирован",
  "Buyurtma allaqachon to'langan yoki bekor qilingan": "Заказ уже оплачен или отменён",
  "Buyurtma holati": "Статус заказа",
  "Buyurtma topilmadi": "Заказ не найден",
  "Buyurtmalarim": "Мои заказы",
  "Buyurtmani bekor qilib bo'lmaydi": "Заказ нельзя отменить",
  "Chegirma": "Скидка",
  "Chiqish": "Выйти",
  "Davom etish orqali": "Продолжая, вы принимаете",
  "Do'kon": "Магазин",
  "Email noto'g'ri": "Неверный email",
  "Email orqali tiklash hozircha yoqilmagan. Do'kon bilan bog'laning, sizga vaqtinchalik parol berishadi.": "Восстановление по email пока не включено. Свяжитесь с магазином — вам выдадут временный пароль.",
  "Email yoki parol noto'g'ri": "Неверный email или пароль",
  "Faqat yetkazib berilgan tovarni baholash mumkin": "Оценить можно только доставленный товар",
  "Fikringiz (ixtiyoriy)": "Ваш отзыв (необязательно)",
  "Foydalanish shartlari (oferta)": "Условия использования (оферта)",
  "Foydalanuvchi topilmadi": "Пользователь не найден",
  "Ha, butunlay o'chirish": "Да, удалить навсегда",
  "Hammasi": "Все",
  "Havola eskirgan yoki noto'g'ri. Qaytadan so'rang": "Ссылка устарела или неверна. Запросите заново",
  "Havola yuborish": "Отправить ссылку",
  "Hech narsa topilmadi.": "Ничего не найдено.",
  "Hisob yaratish": "Создать аккаунт",
  "Hisobingiz va buyurtmalar tarixi butunlay o'chiriladi. Buni qaytarib bo'lmaydi.": "Ваш аккаунт и история заказов будут удалены навсегда. Это нельзя отменить.",
  "Hisobni o'chirish": "Удалить аккаунт",
  "Hozircha buyurtmalar yo'q.": "Заказов пока нет.",
  "Iltimos kuting...": "Пожалуйста, подождите...",
  "Ism-familiya": "Имя и фамилия",
  "Ism-familiyani kiriting": "Введите имя и фамилию",
  "Jami": "Итого",
  "Joriy parol": "Текущий пароль",
  "Joriy parol noto'g'ri": "Неверный текущий пароль",
  "Juda ko'p urinish. Birozdan keyin qayta urinib ko'ring": "Слишком много попыток. Повторите позже",
  "Kamaytirish": "Уменьшить",
  "Kamida 8 belgi": "Минимум 8 символов",
  "Kategoriyalar": "Категории",
  "Kirish": "Войти",
  "Kirish talab qilinadi": "Требуется вход",
  "Kirishga qaytish": "Вернуться ко входу",
  "Ko'paytirish": "Увеличить",
  "Ko'rinish": "Оформление",
  "Ko'rsatish": "Показать",
  "Kunduzgi": "Светлое",
  "Manzil": "Адрес",
  "Maxfiylik siyosati": "Политика конфиденциальности",
  "Mijoz": "Покупатель",
  "O'chirilmoqda...": "Удаление...",
  "Odatiy": "По умолчанию",
  "Olib tashlash": "Убрать",
  "Oxirgi {n} dona": "Осталось {n} шт.",
  "Oxirgi {n} dona qoldi": "Осталось всего {n} шт.",
  "Parol": "Пароль",
  "Parol kamida 8 belgidan iborat bo'lishi kerak": "Пароль должен содержать минимум 8 символов",
  "Parol o'zgartirildi": "Пароль изменён",
  "Parol yangilandi. Endi yangi parol bilan kiring.": "Пароль обновлён. Теперь войдите с новым паролем.",
  "Parolingiz": "Ваш пароль",
  "Parolni ko'rsatish": "Показать пароль",
  "Parolni o'zgartirish": "Изменить пароль",
  "Parolni saqlash": "Сохранить пароль",
  "Parolni tiklash": "Восстановление пароля",
  "Parolni unutdingizmi?": "Забыли пароль?",
  "Parolni yashirish": "Скрыть пароль",
  "Profil": "Профиль",
  "Promokod": "Промокод",
  "Promokod limiti tugagan": "Лимит промокода исчерпан",
  "Promokod muddati tugagan": "Срок действия промокода истёк",
  "Promokod qo'llandi": "Промокод применён",
  "Promokod topilmadi": "Промокод не найден",
  "Qayta buyurtma": "Повторить заказ",
  "Qayta urinish": "Повторить",
  "Qaytarish va almashtirish": "Возврат и обмен",
  "Qimmatroq": "Сначала дорогие",
  "Qo'llash": "Применить",
  "Qo'ng'iroq": "Позвонить",
  "Qulay narxlarda sifatli tovarlar": "Качественные товары по доступным ценам",
  "Rahmat! Fikringiz saqlandi": "Спасибо! Ваш отзыв сохранён",
  "Reyting bo'yicha": "По рейтингу",
  "Ro'yxatdan o'tish": "Регистрация",
  "Saralash": "Сортировка",
  "Savat": "Корзина",
  "Savat bo'sh yoki juda katta": "Корзина пуста или слишком большая",
  "Savatda: {n} · yana qo'shish": "В корзине: {n} · добавить ещё",
  "Savatdagi ba'zi tovarlar endi sotuvda yo'q. Savatni yangilang": "Некоторых товаров из корзины больше нет в продаже. Обновите корзину",
  "Savatdagi tovar ma'lumoti noto'g'ri": "Неверные данные товара в корзине",
  "Savatga qo'shildi": "Добавлено в корзину",
  "Savatga qo'shish": "В корзину",
  "Savatni ko'rish": "Открыть корзину",
  "Sessiya tugagan, qayta kiring": "Сессия истекла, войдите снова",
  "Sevimlilar": "Избранное",
  "Shahar, tuman, ko'cha, uy": "Город, район, улица, дом",
  "Sharhlar": "Отзывы",
  "Sinov rejimi: to'lov haqiqiy pul yechmasdan darhol tasdiqlanadi.": "Тестовый режим: оплата подтверждается сразу, реальные деньги не списываются.",
  "Sotuvchi (administrator)": "Продавец (администратор)",
  "Tayyorlanmoqda": "Готовится",
  "Telefon": "Телефон",
  "Telefon raqami noto'g'ri": "Неверный номер телефона",
  "Telegram orqali yozish": "Написать в Telegram",
  "Til": "Язык",
  "To'landi": "Оплачен",
  "To'lash": "Оплатить",
  "To'lov bekor qilingan": "Оплата отменена",
  "To'lov qabul qilindi. Buyurtmangiz qabul qilindi": "Оплата получена. Ваш заказ принят",
  "To'lov tekshirilmoqda. Holatni Buyurtmalarim bo'limida ko'ring": "Оплата проверяется. Следите за статусом в разделе «Мои заказы»",
  "To'lov usuli hozircha mavjud emas": "Способ оплаты пока недоступен",
  "To'lov usuli mavjud emas": "Способ оплаты недоступен",
  "To'lov kutilmoqda": "Ожидает оплаты",
  "To'langan": "Оплачен",
  "Bekor qilingan": "Отменён",
  "Tovar qidirish": "Поиск товара",
  "Tovar qidirish...": "Поиск товара...",
  "Tovarlar": "Товары",
  "Tovarlarni yuklab bo'lmadi. Internetni tekshirib, qayta urinib ko'ring.": "Не удалось загрузить товары. Проверьте интернет и повторите.",
  "Tovarni baholash": "Оценить товар",
  "Tugagan": "Нет в наличии",
  "Tungi": "Тёмное",
  "Xatolik yuz berdi": "Произошла ошибка",
  "Yangi parol": "Новый пароль",
  "Yangi parol kamida 8 belgidan iborat bo'lishi kerak": "Новый пароль должен содержать минимум 8 символов",
  "Yashirish": "Скрыть",
  "Yetkazib berish": "Доставка",
  "Yetkazib berish ma'lumotlari": "Данные для доставки",
  "Yetkazib berish manzilini kiriting": "Введите адрес доставки",
  "Yetkazildi": "Доставлен",
  "Yo'lda": "В пути",
  "Yopish": "Закрыть",
  "Yuborish": "Отправить",
  "Yuklanmoqda...": "Загрузка...",
  "foydalanish shartlari": "условия использования",
  "ga rozilik bildirasiz.": ".",
  "maxfiylik siyosati": "политику конфиденциальности",
  "va": "и",
  "{sum} dan yuqori buyurtmada yetkazib berish bepul": "Доставка бесплатна при заказе от {sum}",
  "Demo to'lov (sinov)": "Демо-оплата (тест)",
  "Foyda": "Прибыль",
  "so'm": "сум",
  "Sotuvchi": "Продавец",
  "Ko'rinish rejimi": "Режим просмотра",
  "So'rov xato": "Ошибка запроса",
};
